/* Generated by AN DISI Unibo */ 
package it.unibo.buttonqa;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Buttonqa extends QActorMsgQueue{
	public MsgHandle_Buttonqa(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
