/* Generated by AN DISI Unibo */ 
package it.unibo.ledqagui;
import it.unibo.qactors.PlanRepeat;
import it.unibo.qactors.QActorContext;
import it.unibo.qactors.StateExecMessage;
import it.unibo.qactors.QActorUtils;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.action.AsynchActionResult;
import it.unibo.qactors.action.IActorAction;
import it.unibo.qactors.action.IActorAction.ActionExecMode;
import it.unibo.qactors.action.IMsgQueue;
import it.unibo.qactors.akka.QActor;
import it.unibo.qactors.StateFun;
import java.util.Stack;
import java.util.Hashtable;
import java.util.concurrent.Callable;
import alice.tuprolog.Struct;
import alice.tuprolog.Term;
import it.unibo.qactors.action.ActorTimedAction;
public abstract class AbstractLedqagui extends QActor { 
	protected AsynchActionResult aar = null;
	protected boolean actionResult = true;
	protected alice.tuprolog.SolveInfo sol;
	protected String planFilePath    = null;
	protected String terminationEvId = "default";
	protected String parg="";
	protected boolean bres=false;
	protected IActorAction action;
	 
	
		protected static IOutputEnvView setTheEnv(IOutputEnvView outEnvView ){
			return outEnvView;
		}
		public AbstractLedqagui(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
			super(actorId, myCtx,  
			"./srcMore/it/unibo/ledqagui/WorldTheory.pl",
			setTheEnv( outEnvView )  , "init");
			this.planFilePath = "./srcMore/it/unibo/ledqagui/plans.txt";
	  	}
		@Override
		protected void doJob() throws Exception {
			String name  = getName().replace("_ctrl", "");
			mysupport = (IMsgQueue) QActorUtils.getQActor( name ); 
			initStateTable(); 
	 		initSensorSystem();
	 		history.push(stateTab.get( "init" ));
	  	 	autoSendStateExecMsg();
	  		//QActorContext.terminateQActorSystem(this);//todo
		} 	
		/* 
		* ------------------------------------------------------------
		* PLANS
		* ------------------------------------------------------------
		*/    
	    //genAkkaMshHandleStructure
	    protected void initStateTable(){  	
	    	stateTab.put("handleToutBuiltIn",handleToutBuiltIn);
	    	stateTab.put("init",init);
	    	stateTab.put("work",work);
	    	stateTab.put("doJob",doJob);
	    }
	    StateFun handleToutBuiltIn = () -> {	
	    	try{	
	    		PlanRepeat pr = PlanRepeat.setUp("handleTout",-1);
	    		String myselfName = "handleToutBuiltIn";  
	    		println( "ledqagui tout : stops");  
	    		repeatPlanNoTransition(pr,myselfName,"application_"+myselfName,false,false);
	    	}catch(Exception e_handleToutBuiltIn){  
	    		println( getName() + " plan=handleToutBuiltIn WARNING:" + e_handleToutBuiltIn.getMessage() );
	    		QActorContext.terminateQActorSystem(this); 
	    	}
	    };//handleToutBuiltIn
	    
	    StateFun init = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("init",-1);
	    	String myselfName = "init";  
	    	it.unibo.buttonqagui.blsGuiFactory.createLed( myself  );
	    	it.unibo.buttonqagui.blsGuiFactory.turnOff( myself  );
	    	temporaryStr = "\"ledqa STARTS\"";
	    	println( temporaryStr );  
	    	//switchTo work
	        switchToPlanAsNextState(pr, myselfName, "ledqagui_"+myselfName, 
	              "work",false, false, null); 
	    }catch(Exception e_init){  
	    	 println( getName() + " plan=init WARNING:" + e_init.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//init
	    
	    StateFun work = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp(getName()+"_work",0);
	     pr.incNumIter(); 	
	    	String myselfName = "work";  
	    	//bbb
	     msgTransition( pr,myselfName,"ledqagui_"+myselfName,false,
	          new StateFun[]{stateTab.get("doJob") }, 
	          new String[]{"true","M","turn" },
	          60000, "handleToutBuiltIn" );//msgTransition
	    }catch(Exception e_work){  
	    	 println( getName() + " plan=work WARNING:" + e_work.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//work
	    
	    StateFun doJob = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("doJob",-1);
	    	String myselfName = "doJob";  
	    	//onMsg 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("turn(off)");
	    	if( currentMessage != null && currentMessage.msgId().equals("turn") && 
	    		pengine.unify(curT, Term.createTerm("turn(X)")) && 
	    		pengine.unify(curT, Term.createTerm( currentMessage.msgContent() ) )){ 
	    		{/* JavaLikeMove */ 
	    		it.unibo.buttonqagui.blsGuiFactory.turnOff(this );
	    		}
	    	}
	    	//onMsg 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("turn(on)");
	    	if( currentMessage != null && currentMessage.msgId().equals("turn") && 
	    		pengine.unify(curT, Term.createTerm("turn(X)")) && 
	    		pengine.unify(curT, Term.createTerm( currentMessage.msgContent() ) )){ 
	    		{/* JavaLikeMove */ 
	    		it.unibo.buttonqagui.blsGuiFactory.turnOn(this );
	    		}
	    	}
	    	repeatPlanNoTransition(pr,myselfName,"ledqagui_"+myselfName,false,true);
	    }catch(Exception e_doJob){  
	    	 println( getName() + " plan=doJob WARNING:" + e_doJob.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//doJob
	    
	    protected void initSensorSystem(){
	    	//doing nothing in a QActor
	    }
	
	}
