/* Generated by AN DISI Unibo */ 
package it.unibo.ledqagui;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Ledqagui extends QActorMsgQueue{
	public MsgHandle_Ledqagui(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
