/* Generated by AN DISI Unibo */ 
package it.unibo.controlqagui;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Controlqagui extends QActorMsgQueue{
	public MsgHandle_Controlqagui(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
