/* Generated by AN DISI Unibo */ 
package it.unibo.ledqa;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Ledqa extends QActorMsgQueue{
	public MsgHandle_Ledqa(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
