/* Generated by AN DISI Unibo */ 
package it.unibo.ledqamqtt;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Ledqamqtt extends QActorMsgQueue{
	public MsgHandle_Ledqamqtt(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
