/* Generated by AN DISI Unibo */ 
package it.unibo.controlqa;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Controlqa extends QActorMsgQueue{
	public MsgHandle_Controlqa(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
