/* Generated by AN DISI Unibo */ 
package it.unibo.controlqamqtt;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Controlqamqtt extends QActorMsgQueue{
	public MsgHandle_Controlqamqtt(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
