/* Generated by AN DISI Unibo */ 
package it.unibo.buttonqamqtt;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Buttonqamqtt extends QActorMsgQueue{
	public MsgHandle_Buttonqamqtt(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
